# Auto-generated by compose2nix.

{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."ts-" = {
    image = "localhost/compose2nix/ts-";
    environment = {
      "TS_AUTHKEY" = "";
      "TS_DOMAIN_NAME" = "";
      "TS_STATE_DIR" = "/var/lib/tailscale";
    };
    volumes = [
      "/dev/net/tun:/dev/net/tun:rw"
      "tailscale-sidecar_ts-certs:/certs:rw"
      "tailscale-sidecar_ts-state:/var/lib/tailscale:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--cap-add=net_admin"
      "--cap-add=sys_module"
      "--network-alias=tailscale"
      "--network=tailscale-sidecar_default"
    ];
  };
  systemd.services."podman-ts-" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-tailscale-sidecar_default.service"
      "podman-volume-tailscale-sidecar_ts-certs.service"
      "podman-volume-tailscale-sidecar_ts-state.service"
    ];
    requires = [
      "podman-network-tailscale-sidecar_default.service"
      "podman-volume-tailscale-sidecar_ts-certs.service"
      "podman-volume-tailscale-sidecar_ts-state.service"
    ];
    partOf = [
      "podman-compose-tailscale-sidecar-root.target"
    ];
    wantedBy = [
      "podman-compose-tailscale-sidecar-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-tailscale-sidecar_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f tailscale-sidecar_default";
    };
    script = ''
      podman network inspect tailscale-sidecar_default || podman network create tailscale-sidecar_default
    '';
    partOf = [ "podman-compose-tailscale-sidecar-root.target" ];
    wantedBy = [ "podman-compose-tailscale-sidecar-root.target" ];
  };

  # Volumes
  systemd.services."podman-volume-tailscale-sidecar_ts-certs" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect tailscale-sidecar_ts-certs || podman volume create tailscale-sidecar_ts-certs
    '';
    partOf = [ "podman-compose-tailscale-sidecar-root.target" ];
    wantedBy = [ "podman-compose-tailscale-sidecar-root.target" ];
  };
  systemd.services."podman-volume-tailscale-sidecar_ts-state" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect tailscale-sidecar_ts-state || podman volume create tailscale-sidecar_ts-state
    '';
    partOf = [ "podman-compose-tailscale-sidecar-root.target" ];
    wantedBy = [ "podman-compose-tailscale-sidecar-root.target" ];
  };

  # Builds
  systemd.services."podman-build-ts-" = {
    path = [ pkgs.podman pkgs.git ];
    serviceConfig = {
      Type = "oneshot";
      TimeoutSec = 300;
    };
    script = ''
      cd /home/robbiec/Git/tailscale-sidecar
      podman build -t compose2nix/ts- .
    '';
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-tailscale-sidecar-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
